#!/usr/bin/env python
# -*- coding:utf-8 -*-


# ############################################################################
#  license :
# ============================================================================
#
#  File :        TemperatureTransmitter.py
#
#  Project :     EPFL_Industrial_Automation
#
# This file is part of Tango device class.
# 
# Tango is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# Tango is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with Tango.  If not, see <http://www.gnu.org/licenses/>.
# 
#
#  $Author :      luca.joss$
#
#  $Revision :    $
#
#  $Date :        $
#
#  $HeadUrl :     $
# ============================================================================
#            This file is generated by POGO
#     (Program Obviously used to Generate tango Object)
# ############################################################################

__all__ = ["TemperatureTransmitter", "TemperatureTransmitterClass", "main"]

__docformat__ = 'restructuredtext'

import PyTango
import sys
# Add additional import
#----- PROTECTED REGION ID(TemperatureTransmitter.additionnal_import) ENABLED START -----#

#----- PROTECTED REGION END -----#	//	TemperatureTransmitter.additionnal_import

# Device States Description
# No states for this device


class TemperatureTransmitter (PyTango.Device_4Impl):
    """"""
    
    # -------- Add you global variables here --------------------------
    #----- PROTECTED REGION ID(TemperatureTransmitter.global_variables) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	TemperatureTransmitter.global_variables

    def __init__(self, cl, name):
        PyTango.Device_4Impl.__init__(self,cl,name)
        self.debug_stream("In __init__()")
        TemperatureTransmitter.init_device(self)
        #----- PROTECTED REGION ID(TemperatureTransmitter.__init__) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	TemperatureTransmitter.__init__
        
    def delete_device(self):
        self.debug_stream("In delete_device()")
        #----- PROTECTED REGION ID(TemperatureTransmitter.delete_device) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	TemperatureTransmitter.delete_device

    def init_device(self):
        self.debug_stream("In init_device()")
        self.get_device_properties(self.get_device_class())
        self.attr_temperature_read = 0.0
        #----- PROTECTED REGION ID(TemperatureTransmitter.init_device) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	TemperatureTransmitter.init_device

    def always_executed_hook(self):
        self.debug_stream("In always_excuted_hook()")
        #----- PROTECTED REGION ID(TemperatureTransmitter.always_executed_hook) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	TemperatureTransmitter.always_executed_hook

    # -------------------------------------------------------------------------
    #    TemperatureTransmitter read/write attribute methods
    # -------------------------------------------------------------------------
    
    def read_temperature(self, attr):
        self.debug_stream("In read_temperature()")
        #----- PROTECTED REGION ID(TemperatureTransmitter.temperature_read) ENABLED START -----#
        attr.set_value(self.attr_temperature_read)
        
        #----- PROTECTED REGION END -----#	//	TemperatureTransmitter.temperature_read
        
    
    
            
    def read_attr_hardware(self, data):
        self.debug_stream("In read_attr_hardware()")
        #----- PROTECTED REGION ID(TemperatureTransmitter.read_attr_hardware) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	TemperatureTransmitter.read_attr_hardware


    # -------------------------------------------------------------------------
    #    TemperatureTransmitter command methods
    # -------------------------------------------------------------------------
    

    #----- PROTECTED REGION ID(TemperatureTransmitter.programmer_methods) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	TemperatureTransmitter.programmer_methods

class TemperatureTransmitterClass(PyTango.DeviceClass):
    # -------- Add you global class variables here --------------------------
    #----- PROTECTED REGION ID(TemperatureTransmitter.global_class_variables) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	TemperatureTransmitter.global_class_variables


    #    Class Properties
    class_property_list = {
        }


    #    Device Properties
    device_property_list = {
        }


    #    Command definitions
    cmd_list = {
        }


    #    Attribute definitions
    attr_list = {
        'temperature':
            [[PyTango.DevFloat,
            PyTango.SCALAR,
            PyTango.READ]],
        }


def main():
    try:
        py = PyTango.Util(sys.argv)
        py.add_class(TemperatureTransmitterClass, TemperatureTransmitter, 'TemperatureTransmitter')
        #----- PROTECTED REGION ID(TemperatureTransmitter.add_classes) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	TemperatureTransmitter.add_classes

        U = PyTango.Util.instance()
        U.server_init()
        U.server_run()

    except PyTango.DevFailed as e:
        print ('-------> Received a DevFailed exception:', e)
    except Exception as e:
        print ('-------> An unforeseen exception occured....', e)

if __name__ == '__main__':
    main()
