#!/usr/bin/env python
# -*- coding:utf-8 -*-


# ############################################################################
#  license :
# ============================================================================
#
#  File :        WeightTransmitter.py
#
#  Project :     EPFL_Industrial_Automation
#
# This file is part of Tango device class.
# 
# Tango is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# Tango is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with Tango.  If not, see <http://www.gnu.org/licenses/>.
# 
#
#  $Author :      luca.joss$
#
#  $Revision :    $
#
#  $Date :        $
#
#  $HeadUrl :     $
# ============================================================================
#            This file is generated by POGO
#     (Program Obviously used to Generate tango Object)
# ############################################################################

__all__ = ["WeightTransmitter", "WeightTransmitterClass", "main"]

__docformat__ = 'restructuredtext'

import PyTango
import sys
import random
# Add additional import
#----- PROTECTED REGION ID(WeightTransmitter.additionnal_import) ENABLED START -----#

#----- PROTECTED REGION END -----#	//	WeightTransmitter.additionnal_import

# Device States Description
# No states for this device


class WeightTransmitter (PyTango.Device_4Impl):
    """"""
    
    # -------- Add you global variables here --------------------------
    #----- PROTECTED REGION ID(WeightTransmitter.global_variables) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	WeightTransmitter.global_variables

    def __init__(self, cl, name):
        PyTango.Device_4Impl.__init__(self,cl,name)
        self.debug_stream("In __init__()")
        WeightTransmitter.init_device(self)
        #----- PROTECTED REGION ID(WeightTransmitter.__init__) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	WeightTransmitter.__init__
        
    def delete_device(self):
        self.debug_stream("In delete_device()")
        #----- PROTECTED REGION ID(WeightTransmitter.delete_device) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	WeightTransmitter.delete_device

    def init_device(self):
        self.debug_stream("In init_device()")
        self.get_device_properties(self.get_device_class())
        self.attr_weight_read = 0.0
        self.attr_status_read = 0
        #----- PROTECTED REGION ID(WeightTransmitter.init_device) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	WeightTransmitter.init_device

    def always_executed_hook(self):
        self.debug_stream("In always_excuted_hook()")
        #----- PROTECTED REGION ID(WeightTransmitter.always_executed_hook) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	WeightTransmitter.always_executed_hook

    # -------------------------------------------------------------------------
    #    WeightTransmitter read/write attribute methods
    # -------------------------------------------------------------------------
    
    def read_weight(self, attr):
        self.debug_stream("In read_weight()")

	self.attr_weight_read = random.random()*350
        self.debug_stream("New weight reading: " + str(self.attr_weight_read))

        #----- PROTECTED REGION ID(WeightTransmitter.weight_read) ENABLED START -----#
        attr.set_value(self.attr_weight_read)
        
        #----- PROTECTED REGION END -----#	//	WeightTransmitter.weight_read
        
    def read_status(self, attr):
        self.debug_stream("In read_status()")

	self.attr_weight_read = random.randint(0,100)

        #----- PROTECTED REGION ID(WeightTransmitter.status_read) ENABLED START -----#
        attr.set_value(self.attr_status_read)
        
        #----- PROTECTED REGION END -----#	//	WeightTransmitter.status_read
        
    
    
            
    def read_attr_hardware(self, data):
        self.debug_stream("In read_attr_hardware()")
        #----- PROTECTED REGION ID(WeightTransmitter.read_attr_hardware) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	WeightTransmitter.read_attr_hardware


    # -------------------------------------------------------------------------
    #    WeightTransmitter command methods
    # -------------------------------------------------------------------------
    

    #----- PROTECTED REGION ID(WeightTransmitter.programmer_methods) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	WeightTransmitter.programmer_methods

class WeightTransmitterClass(PyTango.DeviceClass):
    # -------- Add you global class variables here --------------------------
    #----- PROTECTED REGION ID(WeightTransmitter.global_class_variables) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	WeightTransmitter.global_class_variables


    #    Class Properties
    class_property_list = {
        }


    #    Device Properties
    device_property_list = {
        }


    #    Command definitions
    cmd_list = {
        }


    #    Attribute definitions
    attr_list = {
        'weight':
            [[PyTango.DevFloat,
            PyTango.SCALAR,
            PyTango.READ],
            {
                'Polling period': "1000",
            } ],
        'status':
            [[PyTango.DevUShort,
            PyTango.SCALAR,
            PyTango.READ],
            {
                'Polling period': "1000",
            } ],
        }


def main():
    try:
        py = PyTango.Util(sys.argv)
        py.add_class(WeightTransmitterClass, WeightTransmitter, 'WeightTransmitter')
        #----- PROTECTED REGION ID(WeightTransmitter.add_classes) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	WeightTransmitter.add_classes

        U = PyTango.Util.instance()
        U.server_init()
        U.server_run()

    except PyTango.DevFailed as e:
        print ('-------> Received a DevFailed exception:', e)
    except Exception as e:
        print ('-------> An unforeseen exception occured....', e)

if __name__ == '__main__':
    main()
