#!/usr/bin/env python
# -*- coding:utf-8 -*-


# ############################################################################
#  license :
# ============================================================================
#
#  File :        PilotValve.py
#
#  Project :     EPFL_Industrial_Automation
#
# This file is part of Tango device class.
# 
# Tango is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# Tango is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with Tango.  If not, see <http://www.gnu.org/licenses/>.
# 
#
#  $Author :      luca.joss$
#
#  $Revision :    $
#
#  $Date :        $
#
#  $HeadUrl :     $
# ============================================================================
#            This file is generated by POGO
#     (Program Obviously used to Generate tango Object)
# ############################################################################

__all__ = ["PilotValve", "PilotValveClass", "main"]

__docformat__ = 'restructuredtext'

import PyTango
import sys
import random
# Add additional import
#----- PROTECTED REGION ID(PilotValve.additionnal_import) ENABLED START -----#

#----- PROTECTED REGION END -----#	//	PilotValve.additionnal_import

# Device States Description
# No states for this device


class PilotValve (PyTango.Device_4Impl):
    """"""
    
    # -------- Add you global variables here --------------------------
    #----- PROTECTED REGION ID(PilotValve.global_variables) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	PilotValve.global_variables

    def __init__(self, cl, name):
        PyTango.Device_4Impl.__init__(self,cl,name)
        self.debug_stream("In __init__()")
        PilotValve.init_device(self)
        #----- PROTECTED REGION ID(PilotValve.__init__) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	PilotValve.__init__
        
    def delete_device(self):
        self.debug_stream("In delete_device()")
        #----- PROTECTED REGION ID(PilotValve.delete_device) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	PilotValve.delete_device

    def init_device(self):
        self.debug_stream("In init_device()")
        self.get_device_properties(self.get_device_class())
        self.attr_valveOpen_read = False
        #----- PROTECTED REGION ID(PilotValve.init_device) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	PilotValve.init_device

    def always_executed_hook(self):
        self.debug_stream("In always_excuted_hook()")
        #----- PROTECTED REGION ID(PilotValve.always_executed_hook) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	PilotValve.always_executed_hook

    # -------------------------------------------------------------------------
    #    PilotValve read/write attribute methods
    # -------------------------------------------------------------------------
    
    def read_valveOpen(self, attr):
        self.debug_stream("In read_valveOpen()")
	i = random.randint(0,1)
	if i==1:
		self.attr_valveOpen_read = True
	else:
		self.attr_valveOpen_read = False
	if self.attr_valveOpen_read:
        	self.debug_stream("Valve is open")
	else:
        	self.debug_stream("Valve is closed")
        #----- PROTECTED REGION ID(PilotValve.valveOpen_read) ENABLED START -----#
        attr.set_value(self.attr_valveOpen_read)
        
        #----- PROTECTED REGION END -----#	//	PilotValve.valveOpen_read
        
    
    
            
    def read_attr_hardware(self, data):
        self.debug_stream("In read_attr_hardware()")
        #----- PROTECTED REGION ID(PilotValve.read_attr_hardware) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	PilotValve.read_attr_hardware


    # -------------------------------------------------------------------------
    #    PilotValve command methods
    # -------------------------------------------------------------------------
    

    #----- PROTECTED REGION ID(PilotValve.programmer_methods) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	PilotValve.programmer_methods

class PilotValveClass(PyTango.DeviceClass):
    # -------- Add you global class variables here --------------------------
    #----- PROTECTED REGION ID(PilotValve.global_class_variables) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	PilotValve.global_class_variables


    #    Class Properties
    class_property_list = {
        }


    #    Device Properties
    device_property_list = {
        }


    #    Command definitions
    cmd_list = {
        }


    #    Attribute definitions
    attr_list = {
        'valveOpen':
            [[PyTango.DevBoolean,
            PyTango.SCALAR,
            PyTango.READ],
            {
                'Polling period': "3000",
            } ],
        }


def main():
    try:
        py = PyTango.Util(sys.argv)
        py.add_class(PilotValveClass, PilotValve, 'PilotValve')
        #----- PROTECTED REGION ID(PilotValve.add_classes) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	PilotValve.add_classes

        U = PyTango.Util.instance()
        U.server_init()
        U.server_run()

    except PyTango.DevFailed as e:
        print ('-------> Received a DevFailed exception:', e)
    except Exception as e:
        print ('-------> An unforeseen exception occured....', e)

if __name__ == '__main__':
    main()
