#!/usr/bin/env python
# -*- coding:utf-8 -*-


# ############################################################################
#  license :
# ============================================================================
#
#  File :        PressureTransmitter.py
#
#  Project :     EPFL_Industrial_Automation
#
# This file is part of Tango device class.
# 
# Tango is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# Tango is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with Tango.  If not, see <http://www.gnu.org/licenses/>.
# 
#
#  $Author :      luca.joss$
#
#  $Revision :    $
#
#  $Date :        $
#
#  $HeadUrl :     $
# ============================================================================
#            This file is generated by POGO
#     (Program Obviously used to Generate tango Object)
# ############################################################################

__all__ = ["PressureTransmitter", "PressureTransmitterClass", "main"]

__docformat__ = 'restructuredtext'

import PyTango
import sys
import random
# Add additional import
#----- PROTECTED REGION ID(PressureTransmitter.additionnal_import) ENABLED START -----#

#----- PROTECTED REGION END -----#	//	PressureTransmitter.additionnal_import

# Device States Description
# No states for this device


class PressureTransmitter (PyTango.Device_4Impl):
    """"""
    
    # -------- Add you global variables here --------------------------
    #----- PROTECTED REGION ID(PressureTransmitter.global_variables) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	PressureTransmitter.global_variables

    def __init__(self, cl, name):
        PyTango.Device_4Impl.__init__(self,cl,name)
        self.debug_stream("In __init__()")
        PressureTransmitter.init_device(self)
        #----- PROTECTED REGION ID(PressureTransmitter.__init__) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	PressureTransmitter.__init__
        
    def delete_device(self):
        self.debug_stream("In delete_device()")
        #----- PROTECTED REGION ID(PressureTransmitter.delete_device) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	PressureTransmitter.delete_device

    def init_device(self):
        self.debug_stream("In init_device()")
        self.get_device_properties(self.get_device_class())
        self.attr_pressure_read = 0.0
        self.attr_status_v_read = 0
        #----- PROTECTED REGION ID(PressureTransmitter.init_device) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	PressureTransmitter.init_device

    def always_executed_hook(self):
        self.debug_stream("In always_excuted_hook()")
        #----- PROTECTED REGION ID(PressureTransmitter.always_executed_hook) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	PressureTransmitter.always_executed_hook

    # -------------------------------------------------------------------------
    #    PressureTransmitter read/write attribute methods
    # -------------------------------------------------------------------------
    
    def read_pressure(self, attr):
        self.debug_stream("In read_pressure()")
	self.attr_pressure_read = random.random()*10000
	self.debug_stream("New pressure reading: " + str(self.attr_pressure_read))
        #----- PROTECTED REGION ID(PressureTransmitter.pressure_read) ENABLED START -----#
        attr.set_value(self.attr_pressure_read)
        
        #----- PROTECTED REGION END -----#	//	PressureTransmitter.pressure_read
        
    def read_status_v(self, attr):
        self.debug_stream("In read_status_v()")
	self.attr_status_v_read = random.randint(0,100)
	self.debug_stream("New status reading: " + str(self.attr_status_v_read))
        #----- PROTECTED REGION ID(PressureTransmitter.status_v_read) ENABLED START -----#
        attr.set_value(self.attr_status_v_read)
        
        #----- PROTECTED REGION END -----#	//	PressureTransmitter.status_v_read
        
    
    
            
    def read_attr_hardware(self, data):
        self.debug_stream("In read_attr_hardware()")
        #----- PROTECTED REGION ID(PressureTransmitter.read_attr_hardware) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	PressureTransmitter.read_attr_hardware


    # -------------------------------------------------------------------------
    #    PressureTransmitter command methods
    # -------------------------------------------------------------------------
    

    #----- PROTECTED REGION ID(PressureTransmitter.programmer_methods) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	PressureTransmitter.programmer_methods

class PressureTransmitterClass(PyTango.DeviceClass):
    # -------- Add you global class variables here --------------------------
    #----- PROTECTED REGION ID(PressureTransmitter.global_class_variables) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	PressureTransmitter.global_class_variables


    #    Class Properties
    class_property_list = {
        }


    #    Device Properties
    device_property_list = {
        }


    #    Command definitions
    cmd_list = {
        }


    #    Attribute definitions
    attr_list = {
        'pressure':
            [[PyTango.DevFloat,
            PyTango.SCALAR,
            PyTango.READ],
            {
                'Polling period': "1000",
            } ],
        'status_v':
            [[PyTango.DevUShort,
            PyTango.SCALAR,
            PyTango.READ],
            {
                'Polling period': "1000",
            } ],
        }


def main():
    try:
        py = PyTango.Util(sys.argv)
        py.add_class(PressureTransmitterClass, PressureTransmitter, 'PressureTransmitter')
        #----- PROTECTED REGION ID(PressureTransmitter.add_classes) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	PressureTransmitter.add_classes

        U = PyTango.Util.instance()
        U.server_init()
        U.server_run()

    except PyTango.DevFailed as e:
        print ('-------> Received a DevFailed exception:', e)
    except Exception as e:
        print ('-------> An unforeseen exception occured....', e)

if __name__ == '__main__':
    main()
