#!/usr/bin/env python
# -*- coding:utf-8 -*-


# ############################################################################
#  license :
# ============================================================================
#
#  File :        PressureValve.py
#
#  Project :     EPFL_Industrial_Automation
#
# This file is part of Tango device class.
# 
# Tango is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# Tango is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with Tango.  If not, see <http://www.gnu.org/licenses/>.
# 
#
#  $Author :      luca.joss$
#
#  $Revision :    $
#
#  $Date :        $
#
#  $HeadUrl :     $
# ============================================================================
#            This file is generated by POGO
#     (Program Obviously used to Generate tango Object)
# ############################################################################

__all__ = ["PressureValve", "PressureValveClass", "main"]

__docformat__ = 'restructuredtext'

import PyTango
import sys
# Add additional import
#----- PROTECTED REGION ID(PressureValve.additionnal_import) ENABLED START -----#

#----- PROTECTED REGION END -----#	//	PressureValve.additionnal_import

# Device States Description
# No states for this device


class PressureValve (PyTango.Device_4Impl):
    """"""
    
    # -------- Add you global variables here --------------------------
    #----- PROTECTED REGION ID(PressureValve.global_variables) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	PressureValve.global_variables

    def __init__(self, cl, name):
        PyTango.Device_4Impl.__init__(self,cl,name)
        self.debug_stream("In __init__()")
        PressureValve.init_device(self)
        #----- PROTECTED REGION ID(PressureValve.__init__) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	PressureValve.__init__
        
    def delete_device(self):
        self.debug_stream("In delete_device()")
        #----- PROTECTED REGION ID(PressureValve.delete_device) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	PressureValve.delete_device

    def init_device(self):
        self.debug_stream("In init_device()")
        self.get_device_properties(self.get_device_class())
        self.attr_valveOpen_read = False
        #----- PROTECTED REGION ID(PressureValve.init_device) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	PressureValve.init_device

    def always_executed_hook(self):
        self.debug_stream("In always_excuted_hook()")
        #----- PROTECTED REGION ID(PressureValve.always_executed_hook) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	PressureValve.always_executed_hook

    # -------------------------------------------------------------------------
    #    PressureValve read/write attribute methods
    # -------------------------------------------------------------------------
    
    def read_valveOpen(self, attr):
        self.debug_stream("In read_valveOpen()")
        #----- PROTECTED REGION ID(PressureValve.valveOpen_read) ENABLED START -----#
        attr.set_value(self.attr_valveOpen_read)
        
        #----- PROTECTED REGION END -----#	//	PressureValve.valveOpen_read
        
    
    
            
    def read_attr_hardware(self, data):
        self.debug_stream("In read_attr_hardware()")
        #----- PROTECTED REGION ID(PressureValve.read_attr_hardware) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	PressureValve.read_attr_hardware


    # -------------------------------------------------------------------------
    #    PressureValve command methods
    # -------------------------------------------------------------------------
    

    #----- PROTECTED REGION ID(PressureValve.programmer_methods) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	PressureValve.programmer_methods

class PressureValveClass(PyTango.DeviceClass):
    # -------- Add you global class variables here --------------------------
    #----- PROTECTED REGION ID(PressureValve.global_class_variables) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	PressureValve.global_class_variables


    #    Class Properties
    class_property_list = {
        }


    #    Device Properties
    device_property_list = {
        }


    #    Command definitions
    cmd_list = {
        }


    #    Attribute definitions
    attr_list = {
        'valveOpen':
            [[PyTango.DevBoolean,
            PyTango.SCALAR,
            PyTango.READ]],
        }


def main():
    try:
        py = PyTango.Util(sys.argv)
        py.add_class(PressureValveClass, PressureValve, 'PressureValve')
        #----- PROTECTED REGION ID(PressureValve.add_classes) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	PressureValve.add_classes

        U = PyTango.Util.instance()
        U.server_init()
        U.server_run()

    except PyTango.DevFailed as e:
        print ('-------> Received a DevFailed exception:', e)
    except Exception as e:
        print ('-------> An unforeseen exception occured....', e)

if __name__ == '__main__':
    main()
